<a href="https://colab.research.google.com/github/Sanjanaashivanand/LearningPytorch/blob/main/Pytorch_Device_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Wed Feb 21 03:33:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [6]:
import torch

#Check if gpu is available
torch.cuda.is_available()

True

In [7]:
#Count the number of devices
torch.cuda.device_count()

1

In [10]:
#Device selection best practice
device = "cuda" if torch.cuda.is_available() else "cpu"

# Put tensors and models and GPU

In [11]:
tensor = torch.tensor([1,2,3]) #default device is cpu
tensor.device

device(type='cpu')

In [12]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving Tensors from GPU to CPU

In [14]:
#Note: numpy does not work on gpu
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [15]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu

tensor([1, 2, 3])

In [16]:
tensor_on_cpu.numpy()

array([1, 2, 3])