<a href="https://colab.research.google.com/github/Sanjanaashivanand/LearningPytorch/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


# Intoduction to Tensors

Creating Tensors

In [3]:
#Different types of tensor

#1. Scalar Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#Check the dimension
scalar.ndim

0

In [5]:
#Get tensor as Python int
scalar.item()

7

In [6]:
#2. Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
#3. Matrix
MATRIX  = torch.tensor([[7,8,4], [9,1,3]])
MATRIX

tensor([[7, 8, 4],
        [9, 1, 3]])

In [9]:
MATRIX.shape

torch.Size([2, 3])

In [10]:
MATRIX.ndim

2

In [11]:
#4. Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [3,4,1]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [3, 4, 1]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 4, 1]])

In [15]:
TENSOR[0,1]

tensor([4, 5, 6])

In [16]:
TENSOR[0,1,1]

tensor(5)

In [17]:
 #Random tensors
random_tensor = torch.rand(3,4,1)
random_tensor

tensor([[[0.5785],
         [0.8356],
         [0.2510],
         [0.2240]],

        [[0.3630],
         [0.4307],
         [0.8046],
         [0.3454]],

        [[0.0852],
         [0.1861],
         [0.9045],
         [0.0243]]])

In [18]:
 #Tensor of zeros
 zeros = torch.zeros(size=(3,3))
 zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
#Tensor of ones
ones = torch.ones(size= (3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
#Tensors in a range
range_tensor = torch.arange(0,20,2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
#Tensor like -> same shape
like = torch.zeros_like(input=range_tensor)
like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatype
*precision in computing*
1. float_32 -> single precision (default)
2. float_16 -> half precision
3. float_64 -> double precision

In [23]:
float_16 = torch.tensor([[3,4,2]],
                        dtype = torch.half,
                        device = None,  #What device your tensor is on
                        requires_grad = False) #track or not to track gradients
float_16

tensor([[3., 4., 2.]], dtype=torch.float16)

In [24]:
#Tensor attributes
print(f"Datatype of the tensor: {float_16.dtype}")
print(f"Shape of the tensor: {float_16.shape}")
print(f"Device the tensor is on: {float_16.device}")

Datatype of the tensor: torch.float16
Shape of the tensor: torch.Size([1, 3])
Device the tensor is on: cpu


## Tensor Operations

In [25]:
tensor = torch.tensor([100,200,300])
tensor

tensor([100, 200, 300])

In [26]:
#Addition
tensor + 10

tensor([110, 210, 310])

In [27]:
#sub
tensor - 10

tensor([ 90, 190, 290])

In [28]:
#Element-wise multiplication
tensor * 10

tensor([1000, 2000, 3000])

In [29]:
#Division
tensor / 10

tensor([10., 20., 30.])

In [30]:
#Matrix Mul
tensor2 = torch.tensor([1,2,3])
torch.matmul(tensor, tensor2)

tensor(1400)

In [31]:
#Transpose
tensor3 = torch.tensor([[1,2,3],
                        [4,5,6]])
print("Before: ", tensor3.shape, tensor3)
print("After: ", tensor3.T.shape, tensor3.T)

Before:  torch.Size([2, 3]) tensor([[1, 2, 3],
        [4, 5, 6]])
After:  torch.Size([3, 2]) tensor([[1, 4],
        [2, 5],
        [3, 6]])


##Tensor Aggregation

In [32]:
x = torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
x.min(), torch.min(x)

(tensor(1), tensor(1))

In [34]:
x.max(), torch.max(x)

(tensor(10), tensor(10))

In [35]:
x.sum(), torch.sum(x)

(tensor(55), tensor(55))

In [36]:
x.type(torch.half).mean(), torch.mean(x.type(torch.half))

(tensor(5.5000, dtype=torch.float16), tensor(5.5000, dtype=torch.float16))

In [37]:
#Find the index of the lowest tensor
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [38]:
#Find the index of the highest tensor
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## Tensor Manipulation

1. Reshape - reshape to a given shape
2. View - reshape but does not change the original value in memory
3. Stacking - combine multiple tensors on top of each other
4. Squeeze - remove one dimension
5. Unsqueeze - add a dimension
6. Permute - return view of the inpu with dimensions swapped(permuted) in a certain way

In [39]:
#Reshape
x_reshaped = x.reshape(2,5)
x.shape, x_reshaped.shape

(torch.Size([10]), torch.Size([2, 5]))

In [40]:
x, x_reshaped

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]))

In [41]:
#View
z = x.view(1,10)
z, x

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [42]:
#changing shape of view changes x
z[:, :5] = 5
z, x

(tensor([[ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10]))

In [43]:
#stack
x_stack = torch.stack([x,x,x], dim=0)
x_stack

tensor([[ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10],
        [ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10],
        [ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10]])

In [44]:
#Squeeze
x_sqeeze = torch.squeeze(x)
x_sqeeze.shape

torch.Size([10])

In [45]:
#Squeeze
x_sqeeze = torch.unsqueeze(x, dim=1)
x_sqeeze.shape, x_sqeeze

(torch.Size([10, 1]),
 tensor([[ 5],
         [ 5],
         [ 5],
         [ 5],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]))

In [46]:
#Permute
img = torch.rand(size=(224,200,3))
x_permute = img.permute(2,0,1)

In [47]:
img.shape, x_permute.shape

(torch.Size([224, 200, 3]), torch.Size([3, 224, 200]))

## Indexing

In [48]:
rand = torch.arange(1,10).reshape(1,3,3)
rand

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [49]:
rand[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
rand[0,0] , rand[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [51]:
rand[0,1,1], rand[0][1][1]

(tensor(5), tensor(5))

In [52]:
rand[:, :, 1]

tensor([[2, 5, 8]])

## Numpy to Tensor

Tensor's default type is float32 but when it converts numpy to tensor, the type is float64

In [58]:
#Convert np array to tensor
np_array = np.random.rand(3, 4)
np_tensor = torch.from_numpy(np_array).type(torch.float32)
np_array, np_tensor

(array([[0.17035369, 0.42020606, 0.17652086, 0.38591744],
        [0.19608496, 0.83403201, 0.31351107, 0.26823847],
        [0.91642065, 0.58563758, 0.50474519, 0.31972589]]),
 tensor([[0.1704, 0.4202, 0.1765, 0.3859],
         [0.1961, 0.8340, 0.3135, 0.2682],
         [0.9164, 0.5856, 0.5047, 0.3197]]))

In [60]:
np_array1 = np_tensor.numpy()
np_array1

array([[0.1703537 , 0.42020607, 0.17652085, 0.38591743],
       [0.19608496, 0.834032  , 0.31351107, 0.26823848],
       [0.91642064, 0.58563757, 0.5047452 , 0.3197259 ]], dtype=float32)

## Reproducbility

Reduce the randomness in neural networks and PyTorch -> random.seed

In [65]:
torch.manual_seed(42)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [66]:
torch.rand(3,4)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [67]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])